// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saptjwlpobjlkutoowpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhcHRqd2xwb2JqbGt1dG9vd3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczMzYwNzMsImV4cCI6MjA5MjkxMjA3M30.7Ydwhcl7CwnGYHhl9w9G-TirsbuUEIw2Qroe26oX8UY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});